name: radarr-tak
summary: UnOfficial release of Radarr
description: |
  Radarr is a movie collection manager for Usenet and BitTorrent users.
  It can monitor multiple RSS feeds for new movies and will interface
  with clients and indexers to grab, sort, and rename them.
  It can also be configured to automatically upgrade the quality
  of existing files in the library when a better quality format becomes
  available. Note that only one type of a given movie is supported.
  If you want both an 4k version and 1080p version of a given movie
  you will need multiple instances.

  The web interface is accessible by default at http://localhost:7878

  See https://radarr.video for more details.

  Radarr Release 5.9.1.9070+
  Core20 is still required for Radarr dependencies
  Service is restarted on any condition.

  Post install commands required to access media folders and see resources :
  sudo snap connect radarr-tak:removable-media
  sudo snap connect radarr-tak:mount-observe
license: MIT
icon: icon.png
grade: stable
confinement: strict
base: core20
adopt-info: radarr

apps:
  radarr:
    command: bin/run-radarr.sh
    daemon: simple
    restart-condition: always
    plugs:
      - mount-observe
      - network
      - network-bind
      - removable-media

parts:
  radarr:
    plugin: nil
    source: 'http://radarr.servarr.com/v1/update/master/updatefile?os=linux&runtime=netcore&arch=x64'
    source-type: tar
    override-build: |
      INST_DIR="$SNAPCRAFT_PART_INSTALL/Radarr"
      mkdir -p "$INST_DIR"
      cp -a * "$INST_DIR"

      snapcraftctl set-version "5.9.1"
    prime:
      - Radarr

  local:
    plugin: dump
    source: snap/local

  deps:
    plugin: dump
    source: .
    stage-packages:
      - liblttng-ust0
      - sqlite3
      - wget
      - libicu66
    stage:
      - usr/bin/sqlite*
      - usr/lib
